spring.application.name=github-final

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/finaldb}
spring.datasource.username=${MYSQL_USER:finaluser}
spring.datasource.password=${MYSQL_PASSWORD:finalpass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.port=8080
